In [50]:
import pandas as pd
import sqlite3

In [51]:
conn = sqlite3.connect("./database.sqlite")

In [52]:
# Create a cursor object

cur = conn.cursor()

In [53]:
cur.execute("select * from content;")

In [54]:
df = pd.read_sql_query("SELECT * FROM content", conn)
df.head()

   reviewid                                            content
0     22703  “Trip-hop” eventually became a ’90s punchline,...
1     22721  Eight years, five albums, and two EPs in, the ...
2     22659  Minneapolis’ Uranium Club seem to revel in bei...
3     22661  Kleenex began with a crash. It transpired one ...
4     22725  It is impossible to consider a given release b...

In [55]:
df_genres = pd.read_sql_query("SELECT * FROM genres", conn)
df_labels = pd.read_sql_query("SELECT * FROM labels", conn)
df_reviews = pd.read_sql_query("SELECT * FROM reviews", conn)
df_years = pd.read_sql_query("SELECT * FROM years", conn)

tables = [df_genres, df_labels, df_reviews, df_years]

In [56]:
for i in tables:
    print(i.columns)

Index(['reviewid', 'genre'], dtype='object')
Index(['reviewid', 'label'], dtype='object')
Index(['reviewid', 'title', 'artist', 'url', 'score', 'best_new_music',
       'author', 'author_type', 'pub_date', 'pub_weekday', 'pub_day',
       'pub_month', 'pub_year'],
      dtype='object')
Index(['reviewid', 'year'], dtype='object')

In [57]:
for i in tables:
    df = pd.merge(df, i, on='reviewid')

In [58]:
print(df.shape)
df.head()

(26018, 17)

,reviewid,content,genre,label,title,artist,url,score,best_new_music,author,author_type,pub_date,pub_weekday,pub_day,pub_month,pub_year,year
0,22703,"“Trip-hop” eventually became a ’90s punchline,...",electronic,virgin,mezzanine,massive attack,http://pitchfork.com/reviews/albums/22703-mezz...,9.3,0,nate patrin,contributor,2017-01-08,6,8,1,2017,1998.0
1,22721,"Eight years, five albums, and two EPs in, the ...",metal,hathenter,prelapsarian,krallice,http://pitchfork.com/reviews/albums/22721-prel...,7.9,0,zoe camp,contributor,2017-01-07,5,7,1,2017,2016.0
2,22659,Minneapolis’ Uranium Club seem to revel in bei...,rock,static shock,all of them naturals,uranium club,http://pitchfork.com/reviews/albums/22659-all-...,7.3,0,david glickman,contributor,2017-01-07,5,7,1,2017,2016.0
3,22659,Minneapolis’ Uranium Club seem to revel in bei...,rock,fashionable idiots,all of them naturals,uranium club,http://pitchfork.com/reviews/albums/22659-all-...,7.3,0,david glickman,contributor,2017-01-07,5,7,1,2017,2016.0
4,22661,Kleenex began with a crash. It transpired one ...,rock,kill rock stars,first songs,"kleenex, liliput",http://pitchfork.com/reviews/albums/22661-firs...,9.0,1,jenn pelly,associate reviews editor,2017-01-06,4,6,1,2017,2016.0

In [59]:
df_dropped_dups = df[df['reviewid'].duplicated() == False]

In [60]:
print(df_dropped_dups.shape)
df_dropped_dups.head()

(18389, 17)

,reviewid,content,genre,label,title,artist,url,score,best_new_music,author,author_type,pub_date,pub_weekday,pub_day,pub_month,pub_year,year
0,22703,"“Trip-hop” eventually became a ’90s punchline,...",electronic,virgin,mezzanine,massive attack,http://pitchfork.com/reviews/albums/22703-mezz...,9.3,0,nate patrin,contributor,2017-01-08,6,8,1,2017,1998.0
1,22721,"Eight years, five albums, and two EPs in, the ...",metal,hathenter,prelapsarian,krallice,http://pitchfork.com/reviews/albums/22721-prel...,7.9,0,zoe camp,contributor,2017-01-07,5,7,1,2017,2016.0
2,22659,Minneapolis’ Uranium Club seem to revel in bei...,rock,static shock,all of them naturals,uranium club,http://pitchfork.com/reviews/albums/22659-all-...,7.3,0,david glickman,contributor,2017-01-07,5,7,1,2017,2016.0
4,22661,Kleenex began with a crash. It transpired one ...,rock,kill rock stars,first songs,"kleenex, liliput",http://pitchfork.com/reviews/albums/22661-firs...,9.0,1,jenn pelly,associate reviews editor,2017-01-06,4,6,1,2017,2016.0
6,22725,It is impossible to consider a given release b...,electronic,teklife,new start,taso,http://pitchfork.com/reviews/albums/22725-new-...,8.1,0,kevin lozano,tracks coordinator,2017-01-06,4,6,1,2017,2016.0

In [61]:
df_dropped_dups.isnull().sum()

reviewid             0
content              0
genre             2365
label               38
title                0
artist               0
url                  0
score                0
best_new_music       0
author               0
author_type       3904
pub_date             0
pub_weekday          0
pub_day              0
pub_month            0
pub_year             0
year               406
dtype: int64